# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.9.1-20230508
    tty: false
    stdin_open: false
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - VNC_NO_PASSWORD=1

  # edge:
  #   image: selenium/node-edge:4.9.1-20230508
  #   tty: false
  #   stdin_open: false
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #     - SE_NODE_MAX_SESSIONS=2
  #     - VNC_NO_PASSWORD=1

  firefox:
    image: selenium/node-firefox:4.9.1-20230508
    tty: false
    stdin_open: false
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - VNC_NO_PASSWORD=1

  selenium-hub:
    image: selenium/hub:4.9.1-20230508
    tty: false
    stdin_open: false
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  node:
    container_name: e2e-tests-container
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /dev/shm:/dev/shm
      - ./report:/usr/app/report
    environment:
      - RUN_IN_DOCKER_COMPOSE=true
      - SELENIUM_GRID_HOST=selenium-hub
    command: ["./bootstrap.sh", "${NODE}"]
    depends_on:
      - chrome
      - firefox
    

  wdio-automation-la:
    image: wdio-automation-la:latest
    container_name: wdio-automation-la
    build: .
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - chrome
      # - edge
      - firefox
    environment:
      - HOST_NAME=selenium-hub
    volumes:
      - ./reporter:/app/reporter